-- FR-014/FR-015: Fraud Alert Review Workflow Audit Table
-- Stores fraud alerts generated by the rule engine for manual review
-- Tracks alert lifecycle from initial detection through confirmation/dismissal

CREATE TABLE IF NOT EXISTS fraud_alerts (
    transaction_id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL,
    matched_rule_names TEXT[] NOT NULL,
    severity TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    evaluation_timestamp BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed-fraud', 'false-positive')),
    reviewed_by TEXT,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    inserted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fraud_alerts_account_id ON fraud_alerts (account_id);
CREATE INDEX IF NOT EXISTS idx_fraud_alerts_status ON fraud_alerts (status);
