-- Iceberg DDL Contract: enriched_transactions v1
-- Source: pipelines/processing/schemas/enriched-txn-v1.avsc
-- Catalog: iceberg (REST catalog, MinIO backend)
-- Generated by: scripts/evolve_iceberg_schema.py
-- Schema version: 1
-- Partition: event_date (DATE derived from event_time), daily

CREATE TABLE IF NOT EXISTS iceberg.enriched_transactions (
    -- Identity
    transaction_id      STRING          NOT NULL,   -- dedup key, partition join key
    account_id          STRING          NOT NULL,
    merchant_id         STRING          NOT NULL,

    -- Transaction core
    amount              DECIMAL(18, 4)  NOT NULL,
    currency            STRING          NOT NULL,   -- ISO-4217
    event_time          TIMESTAMP       NOT NULL,   -- event time; drives daily partition
    enrichment_time     TIMESTAMP       NOT NULL,   -- processing time of sink write
    channel             STRING          NOT NULL,   -- POS/WEB/MOBILE/API

    -- Device / API identity (PCI-DSS scope, PII-masked)
    card_bin            STRING          NOT NULL,
    card_last4          STRING          NOT NULL,
    caller_ip_subnet    STRING          NOT NULL,   -- masked /24
    api_key_id          STRING          NOT NULL,   -- device proxy (v1)
    oauth_scope         STRING          NOT NULL,

    -- Geolocation (raw from API)
    geo_lat             FLOAT,
    geo_lon             FLOAT,

    -- Geolocation (enriched from GeoLite2)
    geo_country         STRING,                     -- ISO 3166-1 alpha-2
    geo_city            STRING,
    geo_network_class   STRING,                     -- RESIDENTIAL/BUSINESS/HOSTING/MOBILE/UNKNOWN
    geo_confidence      FLOAT,                      -- 0.0–1.0

    -- Device fingerprint
    device_first_seen   TIMESTAMP,                  -- null on first transaction per device
    device_txn_count    INT,
    device_known_fraud  BOOLEAN,                    -- always null in v1 (TD-002)
    prev_geo_country    STRING,                     -- previous geo on this device; null on first txn
    prev_txn_time_ms    TIMESTAMP,                  -- previous txn event time; null on first txn

    -- Velocity features (window: 1m)
    vel_count_1m        INT             NOT NULL,
    vel_amount_1m       DECIMAL(18, 4)  NOT NULL,

    -- Velocity features (window: 5m)
    vel_count_5m        INT             NOT NULL,
    vel_amount_5m       DECIMAL(18, 4)  NOT NULL,

    -- Velocity features (window: 1h)
    vel_count_1h        INT             NOT NULL,
    vel_amount_1h       DECIMAL(18, 4)  NOT NULL,

    -- Velocity features (window: 24h)
    vel_count_24h       INT             NOT NULL,
    vel_amount_24h      DECIMAL(18, 4)  NOT NULL,

    -- Processing metadata
    masking_lib_version     STRING      NOT NULL,
    enrichment_latency_ms   INT         NOT NULL,
    processor_version       STRING      NOT NULL,
    schema_version          STRING      NOT NULL    -- default "1"
)
USING iceberg
PARTITIONED BY (days(event_time))
TBLPROPERTIES (
    'write.parquet.compression-codec'   = 'snappy',
    'write.metadata.compression-codec'  = 'gzip',
    'write.target-file-size-bytes'      = '134217728',  -- 128 MiB
    'history.expire.min-snapshots-to-keep' = '10',
    'format-version'                    = '2'
);
